# -*- coding: utf-8 -*-
"""ANN_Assignment_1_Chetan_Pant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cK906IcB4MR7G-bAazMuo2A2AnlrTgKc

## Step 1: Data Understanding
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# evaluation
from sklearn.metrics import confusion_matrix, classification_report

# neural network
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Sem 2 Assignment/telco_churn.csv'
df = pd.read_csv(file_path)

df.head()

df.shape

df.columns

df.info()

df.describe()

df['Churn'].value_counts()

sns.countplot(x='Churn', data=df)
plt.title("Distribution of Customer Churn")
plt.show()

"""## Step 2: Data Cleaning and Preprocessing"""

df = df.drop('customerID', axis=1)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.isnull().sum()

df = df.dropna()

df['Churn'] = df['Churn'].map({'Yes':1, 'No':0})

df.shape

df.dtypes

"""#### TotalCharges contained blank values which were converted to NaN.
#### Since only a small number of rows had missing values, those rows were removed.
"""

categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.shape

df_encoded['Churn'].head()

X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""## Step 3: EDA & Insights"""

contract_churn = pd.crosstab(df['Contract'], df['Churn'])

contract_churn.plot(kind='bar', stacked=True, figsize=(6,4))

plt.title("Churn by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")

plt.show()

plt.figure(figsize=(7,5))

sns.boxplot(x='Churn', y='tenure', data=df)

plt.title("Tenure vs Churn")
plt.show()

plt.figure(figsize=(7,5))

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

plt.title("Monthly Charges vs Churn")

plt.show()

"""## Step 4: Neural Network Modelling"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

y_pred_prob = model.predict(X_test)

"""## Step 5: Evaluation & Interpretation"""

y_pred = (y_pred_prob > 0.5).astype(int)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""## Step 6: From Insights to Decisions
Added on the pdf file


"""